apiVersion: v1
kind: Pod
metadata:
  name: golang-helloworld
  labels:
    app: golang-helloworld
spec:
    containers:
    - name: helloworld
      image: gokulnathb/golang-helloworld:latest
      imagePullPolicy: Always
